Models/Contract.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContractManager1._0.Models
{
    public class Contract
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [DisplayName("Nome do cliente")]
        public string ClientName { get; set; }

        [DisplayName("Tipo do contrato")]
        public ContractType Type { get; set; }

        [DisplayName("Quantidade negociada")]
        public int NegotiatedQuantity { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        [DataType(DataType.Currency)]
        [DisplayName("Valor negociado")]
        public decimal NegotiatedValue { get; set; }

        [DisplayName("Mês/Ano inicio do contrato")]
        [DisplayFormat(DataFormatString = "{0:MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime ContractStart { get; set; }

        [DisplayName("Duração do contrato (meses)")]
        public int Duration { get; set; }

        [DisplayName("PDF do contrato")]
        public string File { get; set; }
    }
}

Models/Enums/ContractType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContractManager1._0.Models
{
    public enum ContractType
    {
        COMPRA = 1,
        VENDA = 2
    }
}

Models/ErrorViewModel.cs
using System;

namespace ContractManager1._0.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContractManager1._0.Dal;
using ContractManager1._0.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Threading;
using System.Reflection;

namespace ContractManager1._0.Controllers
{
    public class ContractsController : Controller
    {
        private readonly ContractManagerContext _context;

        public ContractsController(ContractManagerContext context)
        {
            _context = context;
        }

        // GET: Contracts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contract.ToListAsync());
        }

        // GET: Contracts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // GET: Contracts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contracts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientName,Type,NegotiatedQuantity,NegotiatedValue,ContractStart,Duration,File")] Contract contract, IFormFile file)
        {
            if (file.Length > 0)
            {
                // full path to file in temp location
                var fileName = file.FileName.Replace(" ", "_");
                var path = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ContractFiles", fileName);
                using var stream = new FileStream(path, FileMode.Create);
                
                await file.CopyToAsync(stream);
                contract.File = fileName;
            }
            
            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contract);
        }

        // GET: Contracts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            return View(contract);
        }

        [HttpGet("download")]
        public IActionResult DownloadContract([FromQuery] string file)
        {
            string filePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ContractFiles", file); ;
            string fileName = file;

            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            return File(fileBytes, "application/force-download", fileName);
        }

        // POST: Contracts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClientName,Type,NegotiatedQuantity,NegotiatedValue,ContractStart,Duration")] Contract contract, IFormFile file)
        {
            if (id != contract.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    // full path to file in temp location
                    var fileName = file.FileName.Replace(" ", "_");
                    var path = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "ContractFiles", fileName);
                    using var stream = new FileStream(path, FileMode.Create);

                    await file.CopyToAsync(stream);
                    contract.File = fileName;
                }

                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contract);
        }

        // GET: Contracts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Contracts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _context.Contract.FindAsync(id);
            _context.Contract.Remove(contract);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ContractManager1._0.Models;

namespace ContractManager1._0.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contracts/Create.cshtml
@model ContractManager1._0.Models.Contract

@{
    ViewData["Title"] = "Novo contrato";
}

<h1>Novo contrato</h1>

<h4>Dados do contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type"  asp-items="Html.GetEnumSelectList(typeof(ContractType))" class="form-control"><option value="" selected>--- Selecione ---</option></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegotiatedQuantity" class="control-label"></label>
                <input asp-for="NegotiatedQuantity" class="form-control" />
                <span asp-validation-for="NegotiatedQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegotiatedValue" class="control-label"></label>
                <input asp-for="NegotiatedValue" class="form-control" data-inputmask="'alias': 'numeric', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'placeholder': '0'" />
                <span asp-validation-for="NegotiatedValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractStart" class="control-label"></label>
                <input asp-for="ContractStart" type="month" class="form-control" />
                <span asp-validation-for="ContractStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" type="file" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contracts/Delete.cshtml
@model ContractManager1._0.Models.Contract

@{
    ViewData["Title"] = "Apagar contrato";
}

<h1>Apagar contrato</h1>

<h3>Tem certeza que deseja apagar este contrato?</h3>
<div>
    <h4>Dados do contrato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegotiatedQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegotiatedQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegotiatedValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegotiatedValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.File)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para listagem</a>
    </form>
</div>

Views/Contracts/Details.cshtml
@model ContractManager1._0.Models.Contract

@{
    ViewData["Title"] = "Detalhes do contrato";
}

<h1>Detalhes do contrato</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegotiatedQuantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegotiatedQuantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegotiatedValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegotiatedValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class="col-sm-10">
            <a href="@Url.Action("DownloadContract", "Contracts")?file=@Model.File" target="_blank"><img src="https://www.ufrgs.br/renafor/wp-content/uploads/2018/01/icon-pdf.png" width="64" height="64" border="0" /></a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar contrato</a> |
    <a asp-action="Index">Voltar para listagem</a>
</div>

Views/Contracts/Edit.cshtml
@model ContractManager1._0.Models.Contract

@{
    ViewData["Title"] = "Editar contrato";
}

<h1>Editar contrato</h1>

<h4>Dados do contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" asp-items="Html.GetEnumSelectList(typeof(ContractType))" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegotiatedQuantity" class="control-label"></label>
                <input asp-for="NegotiatedQuantity" class="form-control" />
                <span asp-validation-for="NegotiatedQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegotiatedValue" class="control-label"></label>
                <input asp-for="NegotiatedValue" class="form-control" data-inputmask="'alias': 'numeric', 'autoGroup': true, 'digits': 2, 'digitsOptional': false, 'placeholder': '0'" />
                <span asp-validation-for="NegotiatedValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractStart" class="control-label"></label>
                <input asp-for="ContractStart" type="month" class="form-control" />
                <span asp-validation-for="ContractStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" type="file" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contracts/Index.cshtml
@model IEnumerable<ContractManager1._0.Models.Contract>

@{
    ViewData["Title"] = "Contratos";
}

<h1>Contratos</h1>

<p>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Contracts")'">Novo Contrato</button>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContractStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClientName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContractStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Details", "Contracts", new { @item.Id })'"><i class="fa fa-eye"></i></button>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Contracts", new { @item.Id })'"><i class="fa fa-edit"></i></button>
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Delete", "Contracts", new { @item.Id })'"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao sistema de gerenciamento de contratos da NORUS</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciador de Contratos NORUS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador de Contratos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contracts" asp-action="Index">Contratos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Gerenciador de Contratos NORUS
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js"></script>
   
    @RenderSection("Scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $(":input").inputmask();
        })
    </script>
</body>
</html>